export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_MESSAGE = "CHANGE_MESSAGE";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const CHANGE_QUANTITY_PRODUCT = "CHANGE_QUANTITY_PRODUCT";
