export const MSG_ADD_TO_CART_SUCCESS = 'Thêm vào giỏ hàng thành công!'
export const MSG_UPDATE_CART_SUCCESS = 'Cập nhập giỏ hàng thành công!'
export const MSG_DELETE_PRODUCT_IN_CART_SUCCESS = 'Xóa sản phẩm thành công!'
export const MSG_WELCOME = 'Chào mừng bạn đã đến với cửa hàng!'
export const MSG_CART_EMPTY = 'Chưa có sản phẩm trong giỏ hàng!'